spring:
  threads:
    virtual:
      enabled: true
  application:
    name: aimud
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/aimud
    username: aimud
    password: aimud_password
    pool:
      initial-size: 5
      max-size: 50
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    url: jdbc:postgresql://localhost:5432/aimud
    user: aimud
    password: aimud_password
    clear-checksums: true
  datasource:
    url: jdbc:postgresql://localhost:5432/aimud
    username: aimud
    password: aimud_password
    driver-class-name: org.postgresql.Driver
  docker:
    compose:
      enabled: true
      file: docker-compose.yml
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3.2
      embedding:
        options:
          model: nomic-embed-text
    vectorstore:
      pgvector:
        initialize-schema: false
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 768

