--liquibase formatted sql

--changeset jeff:14 validCheckSum:ANY
ALTER TABLE users ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE users ADD COLUMN modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE users ADD COLUMN created_by VARCHAR(255) DEFAULT 'system';
ALTER TABLE users ADD COLUMN modified_by VARCHAR(255) DEFAULT 'system';

ALTER TABLE characters ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE characters ADD COLUMN modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE characters ADD COLUMN created_by VARCHAR(255) DEFAULT 'system';
ALTER TABLE characters ADD COLUMN modified_by VARCHAR(255) DEFAULT 'system';

ALTER TABLE races ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE races ADD COLUMN modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE races ADD COLUMN created_by VARCHAR(255) DEFAULT 'system';
ALTER TABLE races ADD COLUMN modified_by VARCHAR(255) DEFAULT 'system';

ALTER TABLE character_classes ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE character_classes ADD COLUMN modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE character_classes ADD COLUMN created_by VARCHAR(255) DEFAULT 'system';
ALTER TABLE character_classes ADD COLUMN modified_by VARCHAR(255) DEFAULT 'system';

ALTER TABLE rooms ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE rooms ADD COLUMN modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE rooms ADD COLUMN created_by VARCHAR(255) DEFAULT 'system';
ALTER TABLE rooms ADD COLUMN modified_by VARCHAR(255) DEFAULT 'system';

ALTER TABLE items ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE items ADD COLUMN modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE items ADD COLUMN created_by VARCHAR(255) DEFAULT 'system';
ALTER TABLE items ADD COLUMN modified_by VARCHAR(255) DEFAULT 'system';

ALTER TABLE effects ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE effects ADD COLUMN modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE effects ADD COLUMN created_by VARCHAR(255) DEFAULT 'system';
ALTER TABLE effects ADD COLUMN modified_by VARCHAR(255) DEFAULT 'system';

ALTER TABLE server_settings ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE server_settings ADD COLUMN modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE server_settings ADD COLUMN created_by VARCHAR(255) DEFAULT 'system';
ALTER TABLE server_settings ADD COLUMN modified_by VARCHAR(255) DEFAULT 'system';

ALTER TABLE server_info ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE server_info ADD COLUMN modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE server_info ADD COLUMN created_by VARCHAR(255) DEFAULT 'system';
ALTER TABLE server_info ADD COLUMN modified_by VARCHAR(255) DEFAULT 'system';
