--liquibase formatted sql

--changeset jeff:15
ALTER TABLE users ALTER COLUMN created_at TYPE TIMESTAMP;
ALTER TABLE users ALTER COLUMN modified_at TYPE TIMESTAMP;

ALTER TABLE characters ALTER COLUMN created_at TYPE TIMESTAMP;
ALTER TABLE characters ALTER COLUMN modified_at TYPE TIMESTAMP;

ALTER TABLE races ALTER COLUMN created_at TYPE TIMESTAMP;
ALTER TABLE races ALTER COLUMN modified_at TYPE TIMESTAMP;

ALTER TABLE character_classes ALTER COLUMN created_at TYPE TIMESTAMP;
ALTER TABLE character_classes ALTER COLUMN modified_at TYPE TIMESTAMP;

ALTER TABLE rooms ALTER COLUMN created_at TYPE TIMESTAMP;
ALTER TABLE rooms ALTER COLUMN modified_at TYPE TIMESTAMP;

ALTER TABLE items ALTER COLUMN created_at TYPE TIMESTAMP;
ALTER TABLE items ALTER COLUMN modified_at TYPE TIMESTAMP;

ALTER TABLE effects ALTER COLUMN created_at TYPE TIMESTAMP;
ALTER TABLE effects ALTER COLUMN modified_at TYPE TIMESTAMP;

ALTER TABLE server_settings ALTER COLUMN created_at TYPE TIMESTAMP;
ALTER TABLE server_settings ALTER COLUMN modified_at TYPE TIMESTAMP;

ALTER TABLE server_info ALTER COLUMN created_at TYPE TIMESTAMP;
ALTER TABLE server_info ALTER COLUMN modified_at TYPE TIMESTAMP;
