--changeset antigravity:58
INSERT INTO
    character_classes (
        name,
        description,
        strength_mod,
        intelligence_mod,
        wisdom_mod,
        charisma_mod,
        dexterity_mod,
        constitution_mod,
        npc_only,
        starting_items,
        starting_skills
    )
VALUES
    (
        'Barbarian',
        'A fierce warrior of primitive background who can enter a battle rage.',
        2,
        -1,
        0,
        -1,
        1,
        2,
        true,
        '12,10,8,6,3',
        'Bandage,Light Armor,Medium Armor,Heavy Armor,One Handed Weapon,Two Handed Weapon'
    ),
    (
        'Knight',
        'A heavily armored warrior sworn to a code of conduct and a liege lord.',
        1,
        0,
        1,
        2,
        0,
        1,
        true,
        '12,10,8,6,3',
        'Bandage,Light Armor,Medium Armor,Heavy Armor,One Handed Weapon,Two Handed Weapon'
    ),
    (
        'Cavalier',
        'A mounted combat specialist adept at leading charges.',
        1,
        0,
        0,
        2,
        1,
        1,
        true,
        '12,10,8,6,3',
        'Bandage,Light Armor,Medium Armor,Heavy Armor,One Handed Weapon,Two Handed Weapon'
    ),
    (
        'Gladiator',
        'A pit fighter trained to spill blood for the entertainment of the masses.',
        2,
        -1,
        -1,
        1,
        1,
        2,
        true,
        '12,10,8,6,3',
        'Bandage,Light Armor,Medium Armor,Heavy Armor,One Handed Weapon,Two Handed Weapon'
    ),
    (
        'Mercenary',
        'A professional soldier hired to fight for the highest bidder.',
        1,
        0,
        0,
        0,
        1,
        1,
        true,
        '12,10,8,6,3',
        'Bandage,Light Armor,Medium Armor,Heavy Armor,One Handed Weapon,Two Handed Weapon'
    ),
    (
        'Brawler',
        'An unarmed combat expert relying on brute force and brass knuckles.',
        2,
        -1,
        -1,
        -1,
        1,
        2,
        true,
        '12,10,8,6,3',
        'Bandage,Light Armor,Medium Armor,Heavy Armor,One Handed Weapon,Two Handed Weapon'
    ),
    (
        'Warlord',
        'A commanding battlefield tactician who inspires allies.',
        1,
        1,
        0,
        2,
        0,
        1,
        true,
        '12,10,8,6,3',
        'Bandage,Light Armor,Medium Armor,Heavy Armor,One Handed Weapon,Two Handed Weapon'
    ),
    (
        'Guard',
        'A steadfast defender of city streets and ancient ruins.',
        1,
        0,
        1,
        0,
        0,
        1,
        true,
        '12,10,8,6,3',
        'Bandage,Light Armor,Medium Armor,Heavy Armor,One Handed Weapon,Two Handed Weapon'
    ),
    (
        'Sentinel',
        'A vigilant watcher tasked with guarding sacred sites.',
        1,
        0,
        2,
        0,
        0,
        1,
        true,
        '12,10,8,6,3',
        'Bandage,Light Armor,Medium Armor,Heavy Armor,One Handed Weapon,Two Handed Weapon'
    ),
    (
        'Champion',
        'An elite warrior dedicated to mastering physical prowess.',
        2,
        -1,
        0,
        1,
        1,
        1,
        true,
        '12,10,8,6,3',
        'Bandage,Light Armor,Medium Armor,Heavy Armor,One Handed Weapon,Two Handed Weapon'
    ),
    (
        'Assassin',
        'A shadowy killer specialized in delivering a lethal single strike.',
        0,
        1,
        0,
        -1,
        2,
        0,
        true,
        '11,9,7,4,2',
        'Bandage,Hide,Backstab,Light Armor,One Handed Weapon'
    ),
    (
        'Thief',
        'A quick-fingered burglar adept at bypassing locks and traps.',
        -1,
        1,
        0,
        1,
        2,
        0,
        true,
        '11,9,7,4,2',
        'Bandage,Hide,Backstab,Light Armor,One Handed Weapon'
    ),
    (
        'Bandit',
        'A highway criminal relying on ambushes and intimidation.',
        1,
        -1,
        0,
        -1,
        1,
        1,
        true,
        '11,9,7,4,2',
        'Bandage,Hide,Backstab,Light Armor,One Handed Weapon'
    ),
    (
        'Pirate',
        'A swashbuckling marauder sailing the high seas.',
        1,
        0,
        0,
        2,
        1,
        1,
        true,
        '11,9,7,4,2',
        'Bandage,Hide,Backstab,Light Armor,One Handed Weapon'
    ),
    (
        'Ninja',
        'A heavily trained mystic spy and saboteur.',
        0,
        1,
        1,
        -1,
        2,
        0,
        true,
        '11,9,7,4,2',
        'Bandage,Hide,Backstab,Light Armor,One Handed Weapon'
    ),
    (
        'Scout',
        'An advance recon specialist navigating danger unseen.',
        0,
        1,
        1,
        0,
        2,
        1,
        true,
        '11,9,7,4,2',
        'Bandage,Hide,Backstab,Light Armor,One Handed Weapon'
    ),
    (
        'Bounty Hunter',
        'An unrelenting tracker specializing in capturing fugitives.',
        1,
        1,
        1,
        0,
        1,
        1,
        true,
        '11,9,7,4,2',
        'Bandage,Hide,Backstab,Light Armor,One Handed Weapon'
    ),
    (
        'Smuggler',
        'A covert broker of illicit goods with a silver tongue.',
        -1,
        1,
        0,
        2,
        1,
        0,
        true,
        '11,9,7,4,2',
        'Bandage,Hide,Backstab,Light Armor,One Handed Weapon'
    ),
    (
        'Burglar',
        'A silent infiltrator of high-security fortresses.',
        -1,
        1,
        1,
        0,
        2,
        -1,
        true,
        '11,9,7,4,2',
        'Bandage,Hide,Backstab,Light Armor,One Handed Weapon'
    ),
    (
        'Cutpurse',
        'A lowly street criminal specialized in stealing coin.',
        -1,
        0,
        -1,
        1,
        2,
        -1,
        true,
        '11,9,7,4,2',
        'Bandage,Hide,Backstab,Light Armor,One Handed Weapon'
    ),
    (
        'Summoner',
        'A magic-user who bids ethereal creatures to fight on their behalf.',
        -1,
        3,
        1,
        0,
        0,
        0,
        true,
        '2,17',
        'Bandage,Cast Magic,Light Armor,One Handed Weapon'
    ),
    (
        'Sorcerer',
        'A spellcaster born with profound, innate magical abilities.',
        -1,
        0,
        0,
        3,
        1,
        -1,
        true,
        '2,17',
        'Bandage,Cast Magic,Light Armor,One Handed Weapon'
    ),
    (
        'Warlock',
        'A magic-user who derives their power from a pact with an otherworldly entity.',
        0,
        1,
        0,
        3,
        0,
        0,
        true,
        '2,17',
        'Bandage,Cast Magic,Light Armor,One Handed Weapon'
    ),
    (
        'Necromancer',
        'A dark wizard commanding the forces of death and undeath.',
        -1,
        3,
        0,
        -1,
        0,
        1,
        true,
        '2,17',
        'Bandage,Cast Magic,Light Armor,One Handed Weapon'
    ),
    (
        'Illusionist',
        'A master trickster specializing in deceptive magics.',
        -1,
        3,
        0,
        2,
        1,
        -1,
        true,
        '2,17',
        'Bandage,Cast Magic,Light Armor,One Handed Weapon'
    ),
    (
        'Conjurer',
        'A summoner capable of pulling objects and creatures from the ether.',
        -1,
        3,
        1,
        0,
        0,
        -1,
        true,
        '2,17',
        'Bandage,Cast Magic,Light Armor,One Handed Weapon'
    ),
    (
        'Enchanter',
        'A manipulator of minds who bends others to their will.',
        -1,
        2,
        0,
        3,
        0,
        -1,
        true,
        '2,17',
        'Bandage,Cast Magic,Light Armor,One Handed Weapon'
    ),
    (
        'Invoker',
        'A destructive caster specializing in massive elemental bursts.',
        -1,
        3,
        0,
        0,
        1,
        0,
        true,
        '2,17',
        'Bandage,Cast Magic,Light Armor,One Handed Weapon'
    ),
    (
        'Abjurer',
        'A defensive mage focused on protection and banishment.',
        0,
        3,
        1,
        0,
        0,
        1,
        true,
        '2,17',
        'Bandage,Cast Magic,Light Armor,One Handed Weapon'
    ),
    (
        'Alchemist',
        'A mad scientist brewing powerful potions and explosive concoctions.',
        0,
        3,
        1,
        -1,
        1,
        0,
        true,
        '2,17',
        'Bandage,Cast Magic,Light Armor,One Handed Weapon'
    ),
    (
        'Beast Tamer',
        'A masterful handler of ferocious jungle creatures.',
        1,
        0,
        1,
        -1,
        2,
        1,
        true,
        '11,7,9,4,16',
        'Bandage,Hide,Light Armor,Medium Armor,One Handed Weapon'
    ),
    (
        'Shaman',
        'A spiritual leader channeling the raw elements and ancestral spirits.',
        0,
        0,
        3,
        1,
        0,
        1,
        true,
        '11,7,9,4,16',
        'Bandage,Hide,Light Armor,Medium Armor,One Handed Weapon'
    ),
    (
        'Warden',
        'A heavily armored defender of natural balance.',
        2,
        -1,
        1,
        0,
        0,
        2,
        true,
        '11,7,9,4,16',
        'Bandage,Hide,Light Armor,Medium Armor,One Handed Weapon'
    ),
    (
        'Beastmaster',
        'A wild warrior fighting in tandem with deadly animal companions.',
        1,
        -1,
        1,
        1,
        1,
        2,
        true,
        '11,7,9,4,16',
        'Bandage,Hide,Light Armor,Medium Armor,One Handed Weapon'
    ),
    (
        'Hunter',
        'A specialized slayer of massive beasts and monsters.',
        1,
        0,
        1,
        -1,
        2,
        1,
        true,
        '11,7,9,4,16',
        'Bandage,Hide,Light Armor,Medium Armor,One Handed Weapon'
    ),
    (
        'Hermit',
        'A reclusive wise elder possessing forgotten secrets of the wild.',
        -1,
        1,
        3,
        -2,
        0,
        1,
        true,
        '11,7,9,4,16',
        'Bandage,Hide,Light Armor,Medium Armor,One Handed Weapon'
    ),
    (
        'Pathfinder',
        'An expert guide capable of navigating any treacherous terrain.',
        0,
        1,
        2,
        0,
        1,
        1,
        true,
        '11,7,9,4,16',
        'Bandage,Hide,Light Armor,Medium Armor,One Handed Weapon'
    ),
    (
        'Geomancer',
        'A magic-user who draws power directly from the layout of the earth.',
        0,
        1,
        2,
        -1,
        0,
        2,
        true,
        '11,7,9,4,16',
        'Bandage,Hide,Light Armor,Medium Armor,One Handed Weapon'
    ),
    (
        'Animist',
        'A speaker to spirits residing within stones, trees, and rivers.',
        -1,
        0,
        3,
        1,
        0,
        0,
        true,
        '11,7,9,4,16',
        'Bandage,Hide,Light Armor,Medium Armor,One Handed Weapon'
    ),
    (
        'Inquisitor',
        'A ruthless investigator rooting out heresy and corruption.',
        1,
        1,
        2,
        1,
        0,
        0,
        true,
        '12,10,8,16,6',
        'Bandage,Say Prayer,Light Armor,Medium Armor,Heavy Armor,One Handed Weapon'
    ),
    (
        'Priest',
        'A devout leader tending to the faithful in organized temples.',
        -1,
        1,
        3,
        1,
        -1,
        0,
        true,
        '12,10,8,16,6',
        'Bandage,Say Prayer,Light Armor,Medium Armor,Heavy Armor,One Handed Weapon'
    ),
    (
        'Monk',
        'A disciplined martial artist channeling spiritual ki.',
        0,
        0,
        2,
        0,
        2,
        1,
        true,
        '12,10,8,16,6',
        'Bandage,Say Prayer,Light Armor,Medium Armor,Heavy Armor,One Handed Weapon'
    ),
    (
        'Cultist',
        'A fanatical follower of forbidden, dark entities.',
        0,
        0,
        -1,
        2,
        1,
        0,
        true,
        '12,10,8,16,6',
        'Bandage,Say Prayer,Light Armor,Medium Armor,Heavy Armor,One Handed Weapon'
    ),
    (
        'Oracle',
        'A blessed seer plagued by visions of the past and future.',
        -1,
        1,
        3,
        2,
        -1,
        -1,
        true,
        '12,10,8,16,6',
        'Bandage,Say Prayer,Light Armor,Medium Armor,Heavy Armor,One Handed Weapon'
    ),
    (
        'Templar',
        'An unrelenting holy crusader executing divine judgement.',
        2,
        0,
        1,
        1,
        0,
        1,
        true,
        '12,10,8,16,6',
        'Bandage,Say Prayer,Light Armor,Medium Armor,Heavy Armor,One Handed Weapon'
    ),
    (
        'Chaplain',
        'A field medic providing spiritual and physical relief on the battlefield.',
        0,
        0,
        2,
        2,
        0,
        1,
        true,
        '12,10,8,16,6',
        'Bandage,Say Prayer,Light Armor,Medium Armor,Heavy Armor,One Handed Weapon'
    ),
    (
        'Zealot',
        'A frenzied warrior fueled by religious ecstasy.',
        2,
        -2,
        0,
        1,
        0,
        2,
        true,
        '12,10,8,16,6',
        'Bandage,Say Prayer,Light Armor,Medium Armor,Heavy Armor,One Handed Weapon'
    ),
    (
        'Exorcist',
        'A specialized banisher of demons and possessing spirits.',
        0,
        1,
        3,
        1,
        0,
        0,
        true,
        '12,10,8,16,6',
        'Bandage,Say Prayer,Light Armor,Medium Armor,Heavy Armor,One Handed Weapon'
    ),
    (
        'Aristocrat',
        'A wealthy noble relying on influence, heritage, and coin.',
        -1,
        1,
        0,
        3,
        -1,
        -1,
        true,
        '11,9,7,4,2',
        'Bandage,Light Armor,One Handed Weapon'
    ),
    (
        'Artisan',
        'A master crafter forging exquisite weapons, armors, and goods.',
        1,
        2,
        0,
        0,
        1,
        0,
        true,
        '11,9,7,4,2',
        'Bandage,Light Armor,One Handed Weapon'
    ),
    (
        'Courtesan',
        'An attractive socialite privy to dangerous court secrets.',
        -1,
        1,
        0,
        3,
        1,
        0,
        true,
        '11,9,7,4,2',
        'Bandage,Light Armor,One Handed Weapon'
    ),
    (
        'Beggar',
        'A desperate street-dweller, often surprisingly observant.',
        -1,
        0,
        1,
        -1,
        1,
        -1,
        true,
        '11,9,7,4,2',
        'Bandage,Light Armor,One Handed Weapon'
    ),
    (
        'Blacksmith',
        'A heavy-handed worker of metal and steel.',
        2,
        0,
        0,
        -1,
        0,
        2,
        true,
        '11,9,7,4,2',
        'Bandage,Light Armor,One Handed Weapon'
    ),
    (
        'Carpenter',
        'A builder and shaper of wood.',
        1,
        0,
        0,
        0,
        1,
        1,
        true,
        '11,9,7,4,2',
        'Bandage,Light Armor,One Handed Weapon'
    ),
    (
        'Diplomat',
        'A silver-tongued ambassador brokering peace and treaties.',
        -1,
        2,
        1,
        3,
        0,
        -1,
        true,
        '11,9,7,4,2',
        'Bandage,Light Armor,One Handed Weapon'
    ),
    (
        'Executioner',
        'A grim agent of the law tasked with dealing final blows.',
        2,
        -1,
        0,
        -2,
        0,
        2,
        true,
        '11,9,7,4,2',
        'Bandage,Light Armor,One Handed Weapon'
    ),
    (
        'Farmer',
        'A hardy laborer working the fields.',
        1,
        -1,
        0,
        0,
        0,
        2,
        true,
        '11,9,7,4,2',
        'Bandage,Light Armor,One Handed Weapon'
    ),
    (
        'Fisherman',
        'A patient worker of the rivers and coasts.',
        1,
        -1,
        1,
        -1,
        1,
        1,
        true,
        '11,9,7,4,2',
        'Bandage,Light Armor,One Handed Weapon'
    ),
    (
        'Healer',
        'A trained village physician curing ailments through herbs and remedies.',
        -1,
        2,
        2,
        1,
        0,
        0,
        true,
        '11,9,7,4,2',
        'Bandage,Light Armor,One Handed Weapon'
    ),
    (
        'Innkeeper',
        'A bustling proprietor gathering endless rumors and gossip.',
        0,
        0,
        1,
        2,
        0,
        1,
        true,
        '11,9,7,4,2',
        'Bandage,Light Armor,One Handed Weapon'
    ),
    (
        'Jester',
        'A quick-witted castle clown secretly manipulating the court.',
        -1,
        1,
        0,
        2,
        2,
        0,
        true,
        '11,9,7,4,2',
        'Bandage,Light Armor,One Handed Weapon'
    ),
    (
        'Merchant',
        'A shrewd trader dealing in exotic and mundane goods.',
        -1,
        2,
        1,
        2,
        0,
        0,
        true,
        '11,9,7,4,2',
        'Bandage,Light Armor,One Handed Weapon'
    ),
    (
        'Miner',
        'A rugged digger exploring the deep veins of the earth.',
        2,
        -1,
        0,
        -1,
        0,
        2,
        true,
        '11,9,7,4,2',
        'Bandage,Light Armor,One Handed Weapon'
    ),
    (
        'Sailor',
        'A seasoned deckhand navigating dangerous waters.',
        1,
        0,
        0,
        0,
        2,
        1,
        true,
        '11,9,7,4,2',
        'Bandage,Light Armor,One Handed Weapon'
    ),
    (
        'Scholar',
        'A brilliant academic archiving the world’s history.',
        -1,
        3,
        1,
        0,
        0,
        -1,
        true,
        '11,9,7,4,2',
        'Bandage,Light Armor,One Handed Weapon'
    ),
    (
        'Slaver',
        'A cruel opportunist dealing in the trafficking of lives.',
        1,
        0,
        -1,
        1,
        1,
        1,
        true,
        '11,9,7,4,2',
        'Bandage,Light Armor,One Handed Weapon'
    ),
    (
        'Smith',
        'A skilled metalworker focusing on intricate repairs.',
        1,
        1,
        0,
        0,
        1,
        1,
        true,
        '11,9,7,4,2',
        'Bandage,Light Armor,One Handed Weapon'
    ),
    (
        'Tavern Brawler',
        'A drunken combatant prone to smashing bar stools.',
        2,
        -1,
        -2,
        0,
        -1,
        3,
        true,
        '11,9,7,4,2',
        'Bandage,Light Armor,One Handed Weapon'
    ),
    (
        'Vampire Hunter',
        'A specialized slayer wielding silver and holy water.',
        1,
        1,
        1,
        0,
        1,
        1,
        true,
        '11,9,7,4,2',
        'Bandage,Hide,Backstab,Light Armor,One Handed Weapon'
    ),
    (
        'Demonology Scholar',
        'An academic obsessed with the lower planes.',
        0,
        3,
        0,
        -1,
        0,
        0,
        true,
        '2,17',
        'Bandage,Cast Magic,Light Armor,One Handed Weapon'
    ),
    (
        'Battlemage',
        'A warrior-caster clad in plate mail slinging spells.',
        1,
        2,
        0,
        0,
        0,
        1,
        true,
        '2,17',
        'Bandage,Cast Magic,Light Armor,One Handed Weapon'
    ),
    (
        'Spellblade',
        'An agile fencer infusing their weapon with arcane energy.',
        0,
        2,
        0,
        1,
        2,
        0,
        true,
        '2,17',
        'Bandage,Cast Magic,Light Armor,One Handed Weapon'
    ),
    (
        'Blood Mage',
        'A desperate caster using their own vitality to power spells.',
        -1,
        2,
        0,
        0,
        0,
        3,
        true,
        '2,17',
        'Bandage,Cast Magic,Light Armor,One Handed Weapon'
    ),
    (
        'Death Knight',
        'An undead martial champion of immense necrotic power.',
        3,
        0,
        0,
        1,
        -1,
        2,
        true,
        '12,10,8,6,3',
        'Bandage,Light Armor,Medium Armor,Heavy Armor,One Handed Weapon,Two Handed Weapon'
    ),
    (
        'Dragoon',
        'An aerial combatant specializing in devastating plunging attacks.',
        2,
        0,
        0,
        0,
        2,
        1,
        true,
        '12,10,8,6,3',
        'Bandage,Light Armor,Medium Armor,Heavy Armor,One Handed Weapon,Two Handed Weapon'
    ),
    (
        'Dark Knight',
        'A brooding warrior channeling their pain into dark strikes.',
        2,
        0,
        -1,
        1,
        0,
        2,
        true,
        '12,10,8,6,3',
        'Bandage,Light Armor,Medium Armor,Heavy Armor,One Handed Weapon,Two Handed Weapon'
    ),
    (
        'Sniper',
        'A lethal marksman attacking from impossible distances.',
        0,
        1,
        1,
        -1,
        3,
        0,
        true,
        '11,9,7,4,2',
        'Bandage,Hide,Backstab,Light Armor,One Handed Weapon'
    ),
    (
        'Gunslinger',
        'A fast-drawing pioneer of black powder weaponry.',
        0,
        1,
        0,
        2,
        3,
        0,
        true,
        '11,9,7,4,2',
        'Bandage,Hide,Backstab,Light Armor,One Handed Weapon'
    ),
    (
        'Acrobat',
        'A nimble performer relying on balance and pure speed.',
        -1,
        0,
        0,
        1,
        3,
        0,
        true,
        '11,9,7,4,2',
        'Bandage,Hide,Backstab,Light Armor,One Handed Weapon'
    ),
    (
        'Gladiator Captain',
        'A veteran leader of the blood pits.',
        2,
        0,
        0,
        2,
        1,
        1,
        true,
        '12,10,8,6,3',
        'Bandage,Light Armor,Medium Armor,Heavy Armor,One Handed Weapon,Two Handed Weapon'
    ),
    (
        'Guildmaster',
        'A powerful leader of the thieves or assassins network.',
        0,
        2,
        1,
        3,
        1,
        0,
        true,
        '11,9,7,4,2',
        'Bandage,Hide,Backstab,Light Armor,One Handed Weapon'
    ),
    (
        'Chronomancer',
        'A desperate mage attempting to manipulate the flow of time.',
        0,
        3,
        1,
        -1,
        1,
        -1,
        true,
        '2,17',
        'Bandage,Cast Magic,Light Armor,One Handed Weapon'
    ),
    (
        'Shadowcaster',
        'A rogue wielding physical darkness to blind their foes.',
        -1,
        1,
        0,
        2,
        2,
        0,
        true,
        '11,9,7,4,2',
        'Bandage,Hide,Backstab,Light Armor,One Handed Weapon'
    ),
    (
        'Runesmith',
        'An artisan forging deep magic directly into stone and steel.',
        1,
        2,
        2,
        -1,
        0,
        2,
        true,
        '11,9,7,4,2',
        'Bandage,Light Armor,One Handed Weapon'
    ),
    (
        'Witch',
        'A backwoods mystic brewing hexes and potent charms.',
        -1,
        2,
        2,
        1,
        0,
        -1,
        true,
        '2,17',
        'Bandage,Cast Magic,Light Armor,One Handed Weapon'
    ),
    (
        'Pugilist',
        'A bare-knuckle boxer seeking out the toughest opponents.',
        2,
        -1,
        -1,
        0,
        1,
        3,
        true,
        '12,10,8,6,3',
        'Bandage,Light Armor,Medium Armor,Heavy Armor,One Handed Weapon,Two Handed Weapon'
    ),
    (
        'Psion',
        'An awakened mind manipulating the world through telekinesis.',
        -1,
        4,
        1,
        0,
        -1,
        0,
        true,
        '2,17',
        'Bandage,Cast Magic,Light Armor,One Handed Weapon'
    ),
    (
        'Soulbinder',
        'A ritualist trapping souls in gems for later power.',
        -1,
        3,
        1,
        -1,
        0,
        0,
        true,
        '2,17',
        'Bandage,Cast Magic,Light Armor,One Handed Weapon'
    ),
    (
        'Grave Robber',
        'A scummy scavenger plundering ancient tombs for artifacts.',
        0,
        0,
        -1,
        -1,
        2,
        1,
        true,
        '11,9,7,4,2',
        'Bandage,Hide,Backstab,Light Armor,One Handed Weapon'
    ),
    (
        'Swashbuckler',
        'A charismatic duelist thriving on flair and panache.',
        0,
        1,
        0,
        2,
        2,
        0,
        true,
        '11,9,7,4,2',
        'Bandage,Hide,Backstab,Light Armor,One Handed Weapon'
    ),
    (
        'Artificer',
        'A magical inventor producing wondrous gadgets and constructs.',
        0,
        3,
        0,
        0,
        1,
        0,
        true,
        '11,9,7,4,2',
        'Bandage,Light Armor,One Handed Weapon'
    ),
    (
        'Warlock of the Deep',
        'A cultist drawing power from a submerged, oceanic leviathan.',
        1,
        1,
        0,
        2,
        0,
        1,
        true,
        '2,17',
        'Bandage,Cast Magic,Light Armor,One Handed Weapon'
    ),
    (
        'Hexblade',
        'A cursed warrior drawing their power from a sentient weapon.',
        1,
        0,
        0,
        3,
        1,
        0,
        true,
        '2,17',
        'Bandage,Cast Magic,Light Armor,One Handed Weapon'
    ),
    (
        'Bladesinger',
        'An elegant elven warrior shifting between magic and swordplay.',
        0,
        2,
        0,
        0,
        3,
        0,
        true,
        '2,17',
        'Bandage,Cast Magic,Light Armor,One Handed Weapon'
    ),
    (
        'Warchief',
        'A savage tribal leader charging headfirst into the fray.',
        3,
        0,
        0,
        2,
        0,
        2,
        true,
        '12,10,8,6,3',
        'Bandage,Light Armor,Medium Armor,Heavy Armor,One Handed Weapon,Two Handed Weapon'
    ),
    (
        'Dreadnought',
        'An unstoppable juggernaut relying purely on thick armor and bulk.',
        3,
        -2,
        -1,
        -1,
        -2,
        4,
        true,
        '12,10,8,6,3',
        'Bandage,Light Armor,Medium Armor,Heavy Armor,One Handed Weapon,Two Handed Weapon'
    ),
    (
        'Trickster',
        'A magical scoundrel causing chaos via complex illusions.',
        -1,
        1,
        0,
        3,
        2,
        -1,
        true,
        '2,17',
        'Bandage,Cast Magic,Light Armor,One Handed Weapon'
    ),
    (
        'Vanguard',
        'A heavily shielded shock trooper pushing the front lines.',
        2,
        0,
        0,
        0,
        0,
        3,
        true,
        '12,10,8,6,3',
        'Bandage,Light Armor,Medium Armor,Heavy Armor,One Handed Weapon,Two Handed Weapon'
    ),
    (
        'Mystic',
        'An enigmatic wanderer searching for cosmic enlightenment.',
        -1,
        1,
        3,
        -1,
        1,
        0,
        true,
        '12,10,8,16,6',
        'Bandage,Say Prayer,Light Armor,Medium Armor,Heavy Armor,One Handed Weapon'
    ),
    (
        'Wanderer',
        'A restless traveler with no home and broad, eclectic skills.',
        0,
        0,
        1,
        0,
        1,
        1,
        true,
        '11,9,7,4,2',
        'Bandage,Hide,Backstab,Light Armor,One Handed Weapon'
    );
