--changeset jeff:079-fix-character-inventory
-- Drop the composite primary key that prevents multiple identical items
ALTER TABLE character_inventory DROP CONSTRAINT character_inventory_pkey;

-- Add a new surrogate primary key to uniquely identify every row
ALTER TABLE character_inventory ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;
